In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
columns=['name','age','city','Salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

    name  age      city  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2[['name','city']]

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [14]:
df2['designation']=['doc','engg.','doc','engg.']

In [15]:
df2

    name  age      city  Salary designation
0   John   28  New York   65000         doc
1   Anna   34     Paris   70000       engg.
2  Peter   29    Berlin   62000         doc
3  Linda   42    London   85000       engg.

In [18]:
df2.drop('designation',axis=1,inplace=True)

In [19]:
df2

    name  age      city  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df2.loc[0]

name          John
age             28
city      New York
Salary       65000
Name: 0, dtype: object

In [22]:
df2.loc[[2,3]][['name','age']]

    name  age
2  Peter   29
3  Linda   42

In [32]:
df2[(df2['age']>30 )& (df2['city']=='Paris')]

   name  age   city  Salary
1  Anna   34  Paris   70000

In [30]:
df2

    name  age      city  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000