In [2]:
import numpy as np
import pandas as pd

In [12]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, np.nan],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)

In [4]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False   True   True  False

In [14]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [15]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [18]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN

In [19]:
df.fillna(1)

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  1.0
2  1.0  3.0  3.0  1.0
3  4.0  4.0  1.0  1.0
4  5.0  1.0  1.0  5.0

In [20]:
df

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  NaN  NaN  5.0